import * as H from './harness.mjs';
const t=H.suite('backlinks');await H.start();
const files={'Target.md':'# Target','Other.md':'# Other','wiki.md':'[[Target|name]] [[Target#Heading]]','folder/relative.md':'[target](../Target.md#Heading)','reference.md':'[target][ref]\n\n[ref]: Target.md','ignored.md':'`[[Target]]`\n\n```md\n[[Target]]\n```\n\n<!-- [[Target]] -->\n![image](Target.md) ![[Target]]\n[external](https://example.com/Target.md)','literal.md':'\\[\\[Target]]','draft.md':'No link','.private.md':'[[Target]]'};
const gh=H.fakeGitHub({files}),c=await H.context(gh),p=await H.page(c);p.setDefaultTimeout(5000);await H.signIn(p);await p.waitForFunction(()=>treeState==='ok'&&!pinScanning);await p.evaluate(()=>openFile('Target.md'));
await p.evaluate(()=>{draftStore().setItem(draftKey('draft.md'),JSON.stringify({text:'[[Target]]',sha:'draft'}));document.querySelector('#backlinks').open=true;});await p.waitForFunction(()=>document.querySelector('#backlinks-status').textContent.includes('linking notes'));
const paths=await p.locator('#backlinks-list button').allTextContents();t.check('wikilinks, aliases, relative and reference Markdown links resolve',paths.includes('wiki.md')&&paths.includes('folder/relative.md')&&paths.includes('reference.md'));
t.check('code, comments, embeds, escaped links and external URLs excluded',!paths.includes('ignored.md')&&!paths.includes('literal.md'));
t.check('formatted and URL wikilink aliases resolve across inline tokens',await p.evaluate(()=>['[[Target|*alias*]]','[[Target|**bold**]]','[[Target|https://example.com]]'].every(s=>linkedNotes(s,'source.md').has('Target.md'))));
t.check('escaped wikilinks remain literal',await p.evaluate(()=>!linkedNotes('\\[[Target]]','source.md').has('Target.md')));
t.check('Obsidian comments exclude links without treating code as comments',await p.evaluate(()=>!linkedNotes('%%\n[[Target]]\n\n[link](Target.md)\n%%','source.md').has('Target.md')&&linkedNotes('```\n%%\n```\n[[Target]]','source.md').has('Target.md')));
t.check('local drafts take precedence and hidden files stay hidden',paths.includes('draft.md')&&!paths.includes('.private.md'));t.check('backlink scan never writes notes',gh.commits.length===0);
await p.locator('#backlinks-list button').filter({hasText:'wiki.md'}).click();await p.waitForFunction(()=>current?.path==='wiki.md');t.check('selecting a backlink opens its source',await H.editorValue(p)===files['wiki.md']);
await p.evaluate(()=>openFile('Target.md'));await p.waitForFunction(()=>document.querySelector('#backlinks-status').textContent.includes('linking notes'));
await p.evaluate(()=>resetNoteReads());let entered,release;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);await c.route('**/contents/wiki.md?*',async r=>{entered();await gate;return r.fallback();});await p.evaluate(()=>{window.heldLinks=loadBacklinks();});await started;await p.evaluate(()=>openFile('Other.md'));release();await p.evaluate(()=>heldLinks);await p.waitForFunction(()=>document.querySelector('#backlinks-status').textContent.includes('No linking'));
t.check('late results cannot replace another note backlinks',await p.locator('#backlinks-list button').count()===0);
await c.unroute('**/contents/wiki.md?*');await p.evaluate(()=>{window.marked=null;});await p.evaluate(()=>loadBacklinks());t.check('missing CDN library has a visible fallback',/library could not load/.test(await p.textContent('#backlinks-status')));await c.close();
{
 const source=Object.fromEntries(Array.from({length:305},(_,i)=>['n'+i+'.md','[[Target]] '+i]));source['Target.md']='Target';const gh=H.fakeGitHub({files:source}),c=await H.context(gh),p=await H.page(c);p.setDefaultTimeout(15000);await H.signIn(p);await p.waitForFunction(()=>treeState==='ok'&&!pinScanning);await p.evaluate(()=>openFile('Target.md'));await p.evaluate(()=>resetNoteReads());let reads=0;await c.route('**/contents/n*.md?*',r=>{reads++;return r.fallback();});await p.evaluate(()=>{document.querySelector('#backlinks').open=true;});await p.waitForFunction(()=>document.querySelector('#backlinks-status').textContent.includes('Incomplete'));
 t.check('scan bounded to 300 and labelled incomplete',reads===300&&/5 skipped/.test(await p.textContent('#backlinks-status')));await p.setViewportSize({width:390,height:820});t.check('long backlink lists scroll within phone',await p.locator('#backlinks-list').evaluate(el=>el.scrollHeight>el.clientHeight&&el.clientHeight<=innerHeight*.21));
 await p.evaluate(()=>{resetNoteReads();readFile=async()=>{cfg.token='';cfg.refresh='';throw signedOutError();};});await p.evaluate(()=>loadBacklinks());t.check('expired sign-in prompts instead of hanging',await H.dialogOpen(p));await c.close();
}
await H.stop();t.finish();
