import * as H from './harness.mjs';
const t=H.suite('note-status');await H.start();
const gh=H.fakeGitHub({files:{'a.md':'one two','b.md':'other note'}}),ctx=await H.context(gh),p=await H.page(ctx);
p.setDefaultTimeout(5000);await H.signIn(p);await p.waitForFunction(()=>treeState==='ok'&&!accessPending);await p.evaluate(()=>openFile('a.md'));
const exists=await p.locator('#note-summary').count();t.check('persistent note summary exists',exists===1);
if(exists){
 const status=()=>p.textContent('#note-save-status');
 t.check('loaded note is saved with count',await status()==='Saved'&&await p.textContent('#note-word-count')==='2 words');
 await H.setEditor(p,'one two three');t.check('typing updates unsaved status and count',await status()==='Unsaved changes'&&await p.textContent('#note-word-count')==='3 words');
 let release,entered;const gate=new Promise(r=>release=r),hit=new Promise(r=>entered=r);
 await p.route('**/contents/a.md',async r=>{if(r.request().method()!=='PUT')return r.fallback();entered();await gate;return r.fallback();});
 await p.click('#btn-save');await hit;t.check('in-flight save is visible',await status()==='Saving…');release();await p.waitForFunction(()=>!saving);
 t.check('save records a time',/^Saved/.test(await status())&&/Last saved/.test(await p.textContent('#note-save-time')));
 await p.unroute('**/contents/a.md');await H.setEditor(p,'offline words');
 await p.route('**/contents/a.md',r=>r.abort());await p.click('#btn-save');await p.waitForFunction(()=>!saving);
 t.check('offline saved draft clearly distinguished',/Offline: kept on this device/.test(await status()));
 await p.evaluate(()=>flash('Unrelated operation'));t.check('transient messages cannot hide failed save',/Offline/.test(await status()));
 const sibling=await H.page(ctx);await sibling.waitForFunction(()=>signedIn());
 await sibling.evaluate(()=>localStorage.setItem(draftKey('a.md'),JSON.stringify({text:'other tab words',sha:null})));
 await p.waitForFunction(()=>document.querySelector('#note-save-status').textContent.includes('local copy unavailable'));
 t.check('another tab replacing the draft withdraws reassurance',!/kept on this device/.test(await status()));await sibling.close();
 await p.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('full');};});await H.setEditor(p,'cannot keep this locally');
 t.check('storage failure never claims text is kept',/local copy unavailable/.test(await status())&&!/kept on/.test(await status()));
 await ctx.close();
 const g=H.fakeGitHub({files:{'a.md':'original','b.md':'other'}}),c=await H.context(g),q=await H.page(c);await H.signIn(q);await q.waitForFunction(()=>treeState==='ok'&&!accessPending);await q.evaluate(()=>openFile('a.md'));await H.setEditor(q,'mine');g.files['a.md']='theirs';
 await q.click('#btn-save');await q.waitForFunction(()=>current.conflict&&!saving);
 t.check('conflict remains visible',await q.textContent('#note-save-status')==='Not saved: conflict');
 await q.evaluate(()=>openFile('b.md'));t.check('new note does not inherit conflict or save time',await q.textContent('#note-save-status')==='Saved'&&await q.textContent('#note-save-time')==='');
 await q.click('#btn-preview');t.check('summary remains in Preview',await q.locator('#note-summary').isVisible());
 await c.close();
 const g2=H.fakeGitHub({files:{'a.md':'original'}}),c2=await H.context(g2),p2=await H.page(c2);await H.signIn(p2);await p2.waitForFunction(()=>treeState==='ok'&&!accessPending);await p2.evaluate(()=>openFile('a.md'));
 let finish,started;const wait=new Promise(r=>finish=r),sent=new Promise(r=>started=r);
 await p2.route('**/contents/a.md',async r=>{if(r.request().method()!=='PUT')return r.fallback();started();await wait;return r.abort();});
 await H.setEditor(p2,'new text');await p2.click('#btn-save');await sent;await H.setEditor(p2,'original');finish();await p2.waitForFunction(()=>!saving);
 t.check('uncertain write never claims Saved after undo',/Save outcome unknown/.test(await p2.textContent('#note-save-status')));
 await c2.close();
}else await ctx.close();
await H.stop();t.finish();
