import * as H from './harness.mjs';import{readFileSync}from'node:fs';const t=H.suite('outline');await H.start();
const text='---\ntitle: Metadata\n---\n# First\n\n```md\n# Not a heading\n```\n\nSetext\n------\n\n> ## Quote\n>\n> Paragraph\n\n- item\n\n  ### Nested\n\n## Same\n\n'+('Body paragraph.\n\n'.repeat(45))+'## Same\n\nLast body\n';
for(const plain of [false,true]){
 const gh=H.fakeGitHub({files:{'a.md':text,'b.md':'# Other'}}),c=await H.context(gh,{viewport:{width:390,height:820}});await c.route('**/codemirror/5.65.16/**',r=>{if(plain)return r.abort();const n=new URL(r.request().url()).pathname.split('/').pop();return r.fulfill({contentType:n.endsWith('.css')?'text/css':'application/javascript',headers:{'access-control-allow-origin':'*'},body:n.startsWith('codemirror.min.')?readFileSync(new URL('./fixtures/codemirror5/'+n,import.meta.url)):''});});
 const p=await H.page(c);p.setDefaultTimeout(5000);await H.signIn(p);await p.waitForFunction(()=>treeState==='ok'&&!pinScanning);await p.evaluate(()=>openFile('a.md'));let requests=0;p.on('request',r=>{if(r.url().includes('api.github.com'))requests++;});
 await H.noteAction(p, '#btn-outline');const entries=await p.locator('#outline-list button').allTextContents();t.check(`${plain}: outline includes ATX, setext and nested headings, excludes code/frontmatter`,entries.join('|')==='First|Setext|Quote|Nested|Same|Same');t.check(`${plain}: outline makes no API requests`,requests===0);
 const lines=await p.evaluate(()=>noteHeadings(editor.getValue()).map(h=>h.line));const expected=['# First','Setext','> ## Quote','  ### Nested','## Same'];t.check(`${plain}: source lines map to heading text`,lines.slice(0,5).every((n,i)=>text.split('\n')[n]===expected[i])&&lines[5]===text.split('\n').lastIndexOf('## Same'));
 await p.locator('#outline-list button').last().click();const at=await p.evaluate(()=>editor.caret?editor.caret():editor.indexFromPos(editor.getCursor()));t.check(`${plain}: source jump chooses the second duplicate heading`,at===text.lastIndexOf('## Same'));
 t.check(`${plain}: source jump scrolls the editor`,await p.evaluate(()=>editor.caret?editor.getWrapperElement().scrollTop>0:editor.getScrollInfo().top>0));
 await p.click('#btn-preview');await H.noteAction(p, '#btn-outline');await p.locator('#outline-list button').last().click();t.check(`${plain}: preview jump focuses the matching rendered duplicate`,await p.locator('#pin-list h2').last().evaluate(el=>el===document.activeElement&&el.getBoundingClientRect().top>=document.querySelector('#preview').getBoundingClientRect().top-2));
 t.check(`${plain}: heading navigation never changes source or commits`,await p.evaluate(()=>editor.getValue())===text&&gh.commits.length===0);
 await p.evaluate(()=>{editor.setValue('---\n---\n# First\n\n---\n\n## Second\n');previewView(true,true);});await H.noteAction(p, '#btn-outline');await p.locator('#outline-list button').first().click();t.check(`${plain}: empty frontmatter cannot shift Preview heading targets`,await p.locator('#pin-list h1').evaluate(el=>el===document.activeElement&&el.textContent==='First'));
 t.check(`${plain}: headings nested in quoted lists and tab-indented lists map correctly`,await p.evaluate(()=>['> - first\n>\n>   ## Deep\n','- first\n\n\t## Tab\n','> > # Quote\n','- # First\n- # Second\n'].every(s=>noteHeadings(s).every(h=>Number.isInteger(h.line)&&s.split('\n')[h.line].includes('#')))));
 await p.click('#btn-preview');await p.evaluate(()=>{editor.setValue('# Unsaved heading\n');current.touched=false;clearTimeout(autosaveTimer);});await H.noteAction(p, '#btn-outline');t.check(`${plain}: outline reflects unsaved source`,await p.locator('#outline-list button').allTextContents().then(a=>a.join('|'))==='Unsaved heading');await p.keyboard.press('Escape');t.check(`${plain}: Escape closes outline`,!await p.locator('#outline').evaluate(el=>el.open));
 await H.noteAction(p, '#btn-outline');await p.evaluate(()=>{editor.setValue('# Changed again');});await p.locator('#outline-list button').click();t.check(`${plain}: stale outline refuses to jump`,/note changed/i.test(await p.textContent('#status')));
 await p.evaluate(()=>{editor.setValue('No headings');});await H.noteAction(p, '#btn-outline');t.check(`${plain}: empty state is explicit`,/No headings/.test(await p.textContent('#outline-status')));await p.click('#outline-close');
 await p.evaluate(()=>editor.setValue(Array.from({length:505},(_,i)=>'# Heading '+i+'\n').join('\n')));await H.noteAction(p, '#btn-outline');await p.getByRole('button',{name:'More headings',exact:true}).click();t.check(`${plain}: all headings reachable with bounded pages`,await p.getByRole('button',{name:'Heading 1: Heading 504',exact:true}).count()===1&&await p.locator('#outline-list button').count()===6);await p.getByRole('button',{name:'Previous headings',exact:true}).click();t.check(`${plain}: previous headings page works`,await p.getByRole('button',{name:'Heading 1: Heading 0',exact:true}).count()===1);await p.click('#outline-close');
 await p.evaluate(()=>{window.marked=null;});await H.noteAction(p, '#btn-outline');t.check(`${plain}: missing library is explained`,/library could not load/.test(await p.textContent('#outline-status')));t.check(`${plain}: outline stays within phone width`,await p.locator('#outline').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));await p.evaluate(()=>showSignIn());t.check(`${plain}: sign-in boundary clears the outline`,!await p.locator('#outline').evaluate(el=>el.open)&&await p.locator('#outline-list button').count()===0);await c.close();
}
await H.stop();t.finish();
