blank_issues_enabled: true
contact_links:
  - name: Report a security problem privately
    url: https://github.com/forwardmotionnz/notes/security/advisories/new
    about: Please do not report security problems in a public issue.
